---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: another-kongden-backend-a5c3db8f
  labels:
    app: another-kongden-backend-a5c3db8f
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: another-kongden-backend-a5c3db8f
  template:
    metadata:
      labels:
        app: another-kongden-backend-a5c3db8f
    spec:
      serviceAccountName: ingress-manager
      containers:
        - name: another-kongden-backend-a5c3db8f
          image: docker.io/phengbunath/another-kongden-backend-a5c3db8f:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
